{% set name = "coloc_sat" %}

package:
  name: {{ name|lower }}
  version: {{ environ.get('GIT_DESCRIBE_TAG', 0)}}

source:
  path: ./


build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: 0
  entry_points:
    - Coloc_between_product_and_mission = coloc_sat.scripts.coloc_between_product_and_mission:main
    - Coloc_2_products = coloc_sat.scripts.coloc_2_products:main

requirements:
  build:
    - python >=3.6,<3.12
  host:
    - python >=3.6,<3.12
    - pip
    - setuptools_scm
    - setuptools
  run:
    - python >=3.6,<3.12
    - geopandas
    - xarray-datatree
    - xsar >=2023.8
    - xradarsat2
    - xarray-safe-s1
    - numpy
    - xarray
    - shapely
    - fsspec
    - affine
    - pandas
    - dask
    - more-itertools
    - pyyaml
    - pyproj
    - h5netcdf

test:
  imports:
    - coloc_sat
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/umr-lops/coloc_sat
  summary: 'Python package that enables the co-location of satellite data products, supporting various satellites and missions, including SAR (RCM, RadarSat-2, Sentinel1), WindSat, SMOS, SMAP, ERA5, and HY2.'
  description: |
    coloc_sat is a Python package designed to facilitate the co-location between satellite data products.
    With this package, users can seamlessly combine data from various satellite sources by specifying paths and common variable names. 
    The package offers straightforward installation instructions and usage guidelines, including the ability to generate co-location listings. 
    Supported input satellites and missions include WindSat, SMOS, SMAP, SAR (L1/L2), ERA5, and HY2. Notably, SAR satellites like RCM, RadarSat-2, and Sentinel1 are also supported.
  license: MIT
  license_file: LICENSE
  doc_url: https://coloc-sat.readthedocs.io/
  dev_url: https://github.com/umr-lops/coloc_sat

extra:
  recipe-maintainers:
    - Skealz
    - yreynaud