# Paths to data files
# This example provides multiple paths to give several examples, but only one can be provided,
# or be provided through --mission-products-folder
# Format using %Y, %m, %d and %H should be used in the paths to let the program find the files for the given date.
# The day of year can be used with %(dayOfYear) in the path.
paths:
  SMOS:
    - '/home/ref-smoswind-public/data/v3.0/l3/data/reprocessing/%Y/%(dayOfYear)/*%Y%m%d*.nc'
    - '/home/ref-smoswind-public/data/v3.0/l3/data/nrt/%Y/%(dayOfYear)/*%Y%m%d*.nc'
  HY2:
    - '/home/datawork-cersat-public/provider/knmi/satellite/l2b/hy-2?/hscat/25km/data/%Y/%(dayOfYear)/*%Y%m%d*.nc'
  ASCAT:
    - '/home/datawork-cersat-public/provider/knmi/satellite/l2b/metop-?/ascat/12.5km/data/%Y/%(dayOfYear)/*%Y%m%d*.nc'
  ERA5:
    - '/home/ref-ecmwf/ERA5/%Y/%m/era_5-copernicus__%Y%m%d.nc'
  RS2:
    L1:
      - '/home/datawork-cersat-public/cache/project/sarwing/data/RS2/L1/*/%Y/%(dayOfYear)/RS2*%Y%m%d*'
    L2:
      - '/home/datawork-cersat-public/cache/public/ftp/project/sarwing/processings/c39e79a/default/RS2/*/*/%Y/%(dayOfYear)/RS2_OK*/RS2_*%Y%m%d*/post_processing/nclight_L2M/rs2*owi*%Y%m%d*0003*_ll_gd.nc'
  S1:
    L1:
      - '/home/datawork-cersat-public/cache/project/mpc-sentinel1/data/esa/sentinel-1*/L1/*/*/%Y/%(dayOfYear)/S1*%Y%m%d*SAFE'
    L2:
      - '/home/datawork-cersat-public/cache/public/ftp/project/sarwing/processings/grdwind+windir_2025v6v12_2v0_0v3v9_0v0v8_0v0v8_1v6v0_1v0v15_1v0v14_1v2v8_1v2v12_1v1v1_2v0v8/cmod5n_ecmwf_norecal_rs2rcmgmfv4_16032026/sentinel*/*/*/*/%Y/%(dayOfYear)/S1*%Y%m%d*/post_processing/nclight_L2M_ll_gd/s1*owi*%Y%m%d*0003*_ll_gd.nc'
      #- '/home/datawork-cersat-public/cache/project/sarwing/data/sentinel-1*/*/*/*/%Y/%(dayOfYear)/S1*%Y%m%d*/post_processing/nclight_L2M/s1*owi*%Y%m%d*000003*_ll_gd.nc'
      #- '/home/datawork-cersat-public/cache/public/ftp/project/sarwing/processings/c39e79a/default/sentinel-1*/*/*/*/%Y/%(dayOfYear)/S1*%Y%m%d*/post_processing/nclight_L2M/s1*owi*%Y%m%d*0003*_ll_gd.nc'
  RCM:
    L1:
      - '/home/datawork-cersat-public/provider/asc-csa/satellite/l1/rcm/*/*/*/%Y/%(dayOfYear)/RCM*%Y%m%d*'
    L2:
      - '/home/datawork-cersat-public/cache/public/ftp/project/sarwing/processings/grdwind+windir_2025v6v12_2v0_0v3v9_0v0v8_0v0v8_1v6v0_1v0v15_1v0v14_1v2v8_1v2v12_1v1v1_2v0v8/cmod5n_ecmwf_norecal_rs2rcmgmfv4_16032026/rcm*/*/*/*/%Y/%(dayOfYear)/RCM*%Y%m%d*/post_processing/nclight_L2M_ll_gd/rcm*owi*%Y%m%d*0003*_ll_gd.nc'
  WS:
    - '/home/datawork-cersat-public/project/mpc-sentinel1/analysis/s1_data_analysis/project_rmarquar/wsat/data_compressed/dm/%Y/%(dayOfYear)/wsat_%Y%m%d*.gz'
  SMAP:
    - '/home/datawork-cersat-public/provider/remss/satellite/l3/smap/smap/wind/v1.0/daily/%Y/%(dayOfYear)/RSS_smap_*.nc'
    - '/home/datawork-cersat-public/provider/remss/satellite/l3/smap/smap/wind/v1.0/daily_nrt/%Y/%(dayOfYear)/RSS_smap_*.nc'

# Variables to load for each mission
# The dict key is the mission_name as specified in the mission_name method in the 
# meta class of the mission product (ie. "Soil Moisture and Ocean Salinity")
# The list values are the variables names in the loaded file to keep.
# Lon/lat and time are always loaded, so they don't need to be specified here.
# If nothing is specified for a mission, all variables are loaded.
load_variables:
  "Soil Moisture and Ocean Salinity":
    - wind_speed
    - measurement_time
  "RADARSAT Constellation 2":
    - wind_speed
    - wind_from_direction
    - time

# Dict to rename variables
# This is used by some of the meta mission classes, but not thoroughly implemented yet.
# (ie. rename_vars_in_coloc in smap_meta.py)
common_var_names:
  wind_speed: wind_speed
  wind_direction: wind_direction_ecmwf
  wind_from_direction: wind_from_direction
  longitude: lon
  latitude: lat
  time: time

# Config necessary for parquet script
#dataset_name_1: "S1"
#dataset_name_2: "HY2"
#match_time_accuracy_1: "second"
#match_time_accuracy_2: "minute"
#match_filename_1: false
#match_filename_2: true
#match_time_delta_seconds_1: 0
#match_time_delta_seconds_2: 0

# Not implemented
# multiprocessing can be true, datarmor, or false
#multiprocessing: datarmor
# Memory in GB, useful for datarmor only
#memory: 2
# Nb of workers for multiprocessing mode
#n_workers: 5

