name: Upload package to PyPI

on:
  release:
    types: [created]

jobs:
  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install setuptools_scm
        run: pip install setuptools_scm
      - name: Write version to file
        run: python -c "import setuptools_scm; print(f'__version__ = \\'{setuptools_scm.get_version()}\\'', file=open('coloc_sat/version.py', 'w'))"
      - name: Update system package index
        run: sudo apt update
      - name: Install system packages
        run: sudo apt-get install -y libgdal-dev
      - name: Setup Environment Variables
        run: echo "GDAL_CONFIG=/usr/bin/gdal-config" >> $GITHUB_ENV
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip build twine
          pip install GDAL==`gdal-config --version`
      - name: Build
        run: |
          python -m build --sdist --wheel .
      - name: Check the built archives
        run: |
          twine check dist/*
          pip install dist/*.whl
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@2f6f737ca5f74c637829c0f5c3acd0e29ea5e8bf
        with:
          password: ${{ secrets.pypi_token }}
          repository_url: https://upload.pypi.org/legacy/
          verify_metadata: true
